apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: experimental-ingress
spec:
  rules:
    - host: experimental.clintjedwards.home
      http:
        paths:
          - backend:
              serviceName: experimental-service
              servicePort: 8080
      # This host entry allows us to just type in experimental/
      # once DNS search domains are set up for clients
    - host: experimental
      http:
        paths:
          - backend:
              serviceName: experimental-service
              servicePort: 8080
