name: Build Docker containers

# Only build new container on new tags for master branch
on:
  push:
    tags:
      - "*"

jobs:
  main:
    name: Build and push Docker containers
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker container for amd64 arch
        run: docker build --build-arg GOARCH=amd64 --build-arg SEMVER=$GITHUB_REF -f docker/Dockerfile . -t clintjedwards/experimental:amd64-release-$GITHUB_REF

      - name: Build Docker container for arm64 arch
        run: docker build --build-arg GOARCH=arm64 --build-arg SEMVER=$GITHUB_REF -f docker/Dockerfile . -t clintjedwards/experimental:amd64-release-$GITHUB_REF

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_KEY}}" | docker login --username=cje3295 --password-stdin

      - name: Push image
        run: |
          docker tag clintjedwards/experimental:amd64-release-$GITHUB_REF cje3295/experimental:amd64-release-$GITHUB_REF
          docker tag clintjedwards/experimental:arm64-release-$GITHUB_REF cje3295/experimental:arm64-release-$GITHUB_REF

          docker push cje3295/experimental:amd64-release-$GITHUB_REF
          docker push cje3295/experimental:arm64-release-$GITHUB_REF
